### ISSUE TITLE
Using the script disables touch

### ISSUE THREAD

**Issue by Nimdraug** [Nimdraug/lcdcontrol#1]
Using the script to change the backlighting seems to have somehow turned off the touch capability of my touch screen.
Could also have happened when I was trying to get the HID commands to work correctly and was testing all sorts of things. Or could also be a hardware issue (but I really hope its not).

Going to try and get more information through the HID report and if all else fails, contact Chalkboard Electronics Support.

**Comment by eiGelbGeek** [comment]
Did you find out what the error was?
Did you restore your touchscreen? Or is the touchscreen broken forever? 
Please excuse my bad English ;)

**Comment by Nimdraug** [comment]
The touch screen did not get broken forever, and the touch capability did get restored at some point. But exactly what it was that I did to restore it is a bit of a mystery, and when I reran this script recently, I lost the touch capability again.

Chalkboard Electronics has given me no answers about this.

One possibility could be that the HID commands are meant for the updated firmware which supports multitouch, but I would need to update my firmware to test this.

Unfortunately I have not had the time to debug this, so the script is still not quite usable.

**Comment by Nimdraug** [comment]
I have finally had some time to dedicate to fixing this issue. Turns out that the HIDAPI wrapper library I was using did not de-initialise the HID session correctly.
So I switched HIDAPI wrapper libraries to https://github.com/apmorton/pyhidapi/ and now everything works correctly.
